# Site settings
title: "Tim Klapdor"
tagline: "Technology | Design | Education"
email: tim.klapdor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the resume of Tim Klapdor. Tim trained as a graphic designer and has been working in higher education, originally developing eLearning resources but is now focussed on the underlying technology used in education.  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://timklapdor.com" # the base hostname & protocol for your site

# Collections
collections:
    award:
        output: true
        title: Award
    education: 
        output: true
        title: Education
    experience:
        output: true
        title: Experience
    interests:
        output: true
        title: Interest
    portfolio:
        output: true
        title: Potrtfolio
    publications:
        output: true
        title: Publication
    profile:
        output: true
        title: Profile
    skills:
        output: true
        title: Skills

# Colour Configuration

colour: 
    primary: 8b563F # sets the primary link colour
    secondary: 354257 # sets the hover colour
    text: 1a1a1a # sets text colour
    alternatestripe: aaaaaa # sets the alternate background stripe

# Build settings
markdown: kramdown
highlighter: pygments

excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed
